### PR TITLE
Packet::read/writeLength: optimize bytes written to stream to reduce bandwidth

### PR DESCRIPTION
**Pull request by Bromvlieg**
### Description

By optimizing the bytes we will change an `int64` value of `41` to just a single byte instead of `8` inside the packet class.
Usually you'd write a `vector.size()` or `array.size()` which is a `uint64_t` of `8` bytes, which most often does not go above the range of `uint32_t` of `4` bytes. Most cases we'd save over `50%` of data per size written.

Each number is written per 7 bits, using the highest last bit to indicate if there's still more data to be received

```c++
rawrbox::Packet p;
p.writeLength(0x00); // 1 byte
p.writeLength(0x7F); // 1 byte
p.writeLength(0xFF);  // 2 bytes
p.writeLength(0x7FFF); // 2 bytes
p.writeLength(0xFFFF); // 3 bytes
p.writeLength(0x7FFFFFFF); // 4 bytes
p.writeLength(0xFFFFFFFF); // 5 bytes
p.writeLength(0x7FFFFFFFFFFFFFFF); //8 bytes
p.writeLength(0xFFFFFFFFFFFFFFFF); // 9 bytes
```

### CODE REVIEW

**Comment by edunad** [comment]
Looks good, fix the linter issues

**Review by edunad — CHANGES_REQUESTED** [review]
Fix linter

**Comment by Bromvlieg** [comment]
https://github.com/cpp-linter/cpp-linter-action/issues/161

🤷

**Comment by 2bndy5** [comment]
> Fix linter

@edunad It wouldn't hurt to have some contribution guidelines to explain what clang-format is used for in this repo. More importantly, what version of clang-format to use on devs' local machine because the latest release is not guaranteed to be compatible with the version used in your CI.

@Bromvlieg install clang-format v16 (see [LLVM release](https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.4) for download links) and run (from repo root)
```shell
clang-format -style=file network/include/rawrbox/network/packet.hpp
```
or use a [VSCode extension for clang-format](https://marketplace.visualstudio.com/items?itemName=xaver.clang-format).

**Comment by edunad** [comment]
> > Fix linter
> 
> @edunad It wouldn't hurt to have [the contribution guidelines](https://github.com/edunad/rawrbox/blob/master/CONTRIBUTING.md) explain what clang-format is used for in this repo. More importantly, what version of clang-format to use on devs' local machine because the latest release is not guaranteed to be compatible with the version used in your CI.
> 
> @Bromvlieg install clang-format v16 (see [LLVM release](https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.4) for download links) and run (from repo root)
> 
> ```shell
> clang-format -style=file network/include/rawrbox/network/packet.hpp
> ```
> 
> or use a [VSCode extension for clang-format](https://marketplace.visualstudio.com/items?itemName=xaver.clang-format).

hey :D, I'll add the clang version we use to the contributions, regarding the vs extension, we are using it and files are being formatted, that's why we are a bit confused

**Comment by 2bndy5** [comment]
> Every time I press save it re-applies the format :(

Check your VSCode settings. It might be set to use a different formatter when it saves a C/C++ file.

**Comment by Bromvlieg** [comment]
From what I can tell it uses the correct clang-format version and is set as the formatter. I'll try to test it on my home computer later if it has the same issue as the computer I'm on now.
image

**Comment by 2bndy5** [comment]
Also make sure clang-format is set to use .clang-format file (`-style=file`). Personally, I disable auto-formatting on-file-save.

**Comment by Bromvlieg** [comment]
Same behavior at home, double checked settings, could not get it to work.
Ended up just pressing F1 -> save without formatting and commiting.

**Review by edunad — APPROVED** [review]

**Pull request merged**
